hoistPattern:
  - '*'
hoistedDependencies: {}
included:
  dependencies: true
  devDependencies: true
  optionalDependencies: true
layoutVersion: 5
packageManager: pnpm@6.24.1
pendingBuilds: []
prunedAt: Fri, 14 Jan 2022 06:03:46 GMT
publicHoistPattern:
  - '*'
registries:
  default: https://registry.npmjs.org/
skipped:
  - /esbuild-android-arm64/0.13.15
  - /esbuild-darwin-64/0.13.15
  - /esbuild-darwin-arm64/0.13.15
  - /esbuild-freebsd-64/0.13.15
  - /esbuild-freebsd-arm64/0.13.15
  - /esbuild-linux-32/0.13.15
  - /esbuild-linux-64/0.13.15
  - /esbuild-linux-arm/0.13.15
  - /esbuild-linux-arm64/0.13.15
  - /esbuild-linux-mips64le/0.13.15
  - /esbuild-linux-ppc64le/0.13.15
  - /esbuild-netbsd-64/0.13.15
  - /esbuild-openbsd-64/0.13.15
  - /esbuild-sunos-64/0.13.15
  - /esbuild-windows-32/0.13.15
  - /esbuild-windows-arm64/0.13.15
  - /fsevents/2.3.2
storeDir: F:\.pnpm-store\v3
virtualStoreDir: F:\book-main\node_modules\.pnpm
